package tobacco.game.test.entities;

import tobacco.core.entities.Entity;

public interface EntityFactory {

	/**
	 * Creates an {@link Entity}. Implementations define
	 * associated {@link Component}s.
	 * @return an {@link Entity} generated by this factory.
	 */
	public Entity create();

}