/*******************************************************************************
 * Tobacco - A portable and reusable game engine written in Java.
 * Copyright © 2015 Nirei
 *
 * This file is part of Tobacco
 *
 * Tobacco is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/
package tobacco.core.entities;

import java.util.Collection;

import tobacco.core.components.Component;

/**
 * A generic entity factory.
 * @author nirei
 */
public class EntityFactory {
	
	private EntityService entServ;

	public EntityFactory(EntityService entServ) {
		this.entServ = entServ;
	}
	
	/**
	 * Creates a blank {@link Entity}.
	 * @return an {@link Entity} generated by this factory.
	 */
	public Entity create() {
		return entServ.create();
	}
	
	/**
	 * Creates an {@link Entity} containing the specified components.
	 * @param comps - a {@link Collection} of components.
	 * @return an {@link Entity} populated with specified components.
	 */
	public Entity create(Collection<Component> comps) {
		Entity ent = entServ.create();
		for(Component c : comps) {
			ent.add(c);
		}
		return ent;
	}
}