package tobacco.core.entities;

import java.util.Collection;

import tobacco.core.components.Component;
import tobacco.core.services.Directory;

/**
 * A generic entity factory.
 * @author nirei
 */
public class EntityFactory {

	public EntityFactory() {}
	
	/**
	 * Creates a blank {@link Entity}.
	 * @return an {@link Entity} generated by this factory.
	 */
	public Entity create() {
		return Directory.getEntityService().create();
	}
	
	/**
	 * Creates an {@link Entity} containing the specified components.
	 * @param comps - a {@link Collection} of components.
	 * @return an {@link Entity} populated with specified components.
	 */
	public Entity create(Collection<Component> comps) {
		Entity ent = create();
		for(Component c : comps) {
			ent.add(c);
		}
		return ent;
	}
}